### PR TITLE
feat: Add PSS signing and verifying

### PR DESCRIPTION
**Pull request by Andrew-Lees11**
## Description

This pull request adds `usePSS` flag to sign and verify. This allows you to use RSA-PSS for signing and verifying. If the flag is set to true the functions will use `RSA_PKCS1_PSS_PADDING`, a salt the length of the digest and MGF1 mask generation function to sign or verify. 

## Motivation and Context
This change is required because  "In general, RSA-PSS should be used as a replacement for RSA-PKCS#1 v1.5".

It also allows us to support PS256 and PS384 signing/verifying with JWTs as requested by SwiftJWT issue #[55](https://github.com/IBM-Swift/Swift-JWT/issues/55)

## How Has This Been Tested?
Tests have been added covering the new algorithms and the produced signatures have been tested against JWT.io both that one we create is valid and we can verify a valid one created by JWT.io.

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by Andrew-Lees11** [comment]
@billabt Would you be able to have a look at this and if you are happy squash merge and tag the change?

**Comment by Andrew-Lees11** [comment]
We tested for Memory leaks and there aren't any in the new PSS paths. We did find one in make keys and have added a Deallocate to the `getPEMString` function which solves this.

**Comment by billabt** [comment]
@Andrew-Lees11 Had to change your _available_ statements for using PSS.  The correct **iOS** version is **11.0** not 10.  It showed up here when I built the package for iOS something we don't do for CI.  I fixed it after the merge.  Just an FYI.

**Comment by billabt** [comment]
@Andrew-Lees11 Had to make another change to the tests.  They were generating warning on Swift 4.0.3.

**Comment by Andrew-Lees11** [comment]
PSS is only supported from Swift 4.1 onwards which must be iOS 11. Thank you for spotting and fixing this.

**Pull request merged**
